(()=>{'use strict';
const K=window.SeowooCore,G=window.SeowooGames,{C,state,audio,setting,save,reset,numberSpeech,toast,awardSticker,confetti,recordChoice,complete,shuffle,rand,difficultyLevel}=K;
const main=document.querySelector('#main');
let route='home',rhythmTimer=null,wordFilter={en:'전체',ko:'전체'};
let routeEpoch=0;const timers=new Set();
function later(fn,ms){const epoch=routeEpoch;const t=setTimeout(()=>{timers.delete(t);if(epoch===routeEpoch)fn()},ms);timers.add(t);return t}
const potty={step:0,kind:null,wash:0,flushing:false};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function stopTimers(){routeEpoch++;for(const t of timers)clearTimeout(t);timers.clear();G.stop?.();clearInterval(rhythmTimer);rhythmTimer=null}
function go(name,opt={}){audio.unlock();audio.stop();stopTimers();route=name;try{sessionStorage.setItem('seowoo-route',name)}catch{}render(opt);window.dispatchEvent(new CustomEvent('seowoo:route',{detail:{route:name}}));window.scrollTo({top:0,behavior:'smooth'})}
function back(){go('home')}
function subhead(title,sub=''){return`<div class="subhead"><button class="back-btn" data-go="home" aria-label="놀이터로 돌아가기">←</button><div><h1>${title}</h1>${sub?`<small>${sub}</small>`:''}</div></div>`}
function wireGo(){main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));main.querySelectorAll('[data-back]').forEach(b=>b.onclick=back)}
function render(){switch(route){case'home':renderHome();break;case'numbers':renderNumbers();break;case'numberBoard':renderNumberBoard();break;case'quantity':G.startQuantity(main);break;case'numberOrder':G.startNumberOrder(main);break;case'finger':startFinger(main);break;case'elevator':renderElevator();break;case'language':renderLanguage();break;case'alphabet':renderAlphabet();break;case'englishWords':renderWords('en');break;case'koreanWords':renderWords('ko');break;case'hangul':renderHangul();break;case'think':renderThink();break;case'color':G.startColor(main);break;case'shape':G.startShape(main);break;case'memory':G.startMemory(main);break;case'potty':renderPotty();break;case'together':renderTogether();break;case'music':renderMusic();break;case'treasure':renderTreasure();break;case'parent':renderParentGate();break;default:renderHome()}wireGo();updateHeader()}
const NAV_ICONS={"numbers":"<rect x=\"5\" y=\"5\" width=\"38\" height=\"38\" rx=\"10\"/><path d=\"M15 15h4v18m9-18h6v8h-6v10h6\"/>","elevator":"<rect x=\"7\" y=\"4\" width=\"34\" height=\"40\" rx=\"5\"/><path d=\"M12 16h24v25H12zm12 0v25M17 10l3-3 3 3m5-3 3 3 3-3\"/>","language":"<path d=\"M6 10q9-4 18 2 9-6 18-2v28q-9-4-18 2-9-6-18-2zM24 12v28M12 19h6m-6 7h6m12-7h6m-6 7h6\"/>","think":"<path d=\"M24 5a14 14 0 0 0-9 25l3 5h12l3-5A14 14 0 0 0 24 5ZM18 40h12M21 44h6M20 20l4 5 6-9\"/>","potty":"<path d=\"M27 7h12v18H27zm-18 18h30v4c0 7-6 9-10 9v6H18v-6c-5-1-9-5-9-9zM32 12h3\"/>","music":"<path d=\"M19 33V10l22-5v23M19 15l22-5\"/><ellipse cx=\"12\" cy=\"35\" rx=\"7\" ry=\"5\"/><ellipse cx=\"34\" cy=\"30\" rx=\"7\" ry=\"5\"/>","together":"<circle cx=\"16\" cy=\"13\" r=\"6\"/><circle cx=\"34\" cy=\"17\" r=\"5\"/><path d=\"M5 40V30a11 11 0 0 1 22 0v10m0-12a9 9 0 0 1 16 6v6M12 32v8m8-8v8m14-6v6\"/>"};
function icon(route,fallback){return NAV_ICONS[route]?'<svg class="nav-icon" aria-hidden="true" viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">'+NAV_ICONS[route]+'</svg>':fallback}
function cat(goTo,e,t,s,c){return`<button class="category-card ${c}" data-go="${goTo}"><span class="emoji">${icon(goTo,e)}</span><span><b>${t}</b><small>${s}</small></span></button>`}
function tile(goTo,e,t,s){return`<button class="tile" data-go="${goTo}"><span class="emoji">${e}</span><b>${t}</b><small>${s}</small></button>`}
function renderHome(){const today=state.recent.filter(x=>new Date(x.at).toDateString()===new Date().toDateString()).length;main.innerHTML=`<section class="hero"><div class="hero-row"><div class="mascot">⭐</div><div><h1>서우야, 오늘 뭐 하고 놀까?</h1><p>숫자도, 말도, 생활습관도 재미있게!</p></div></div><div class="today-row"><span class="pill">⭐ 스티커 ${state.stickers.length}개</span><span class="pill">🎈 오늘 놀이 ${today}개</span></div></section><div class="section-title"><h2>놀이마을</h2><p>큰 카드를 톡 눌러봐</p></div><div class="category-grid">${cat('numbers','🔢','숫자 놀이터','1부터 100까지 신나게','c-sky')}${cat('elevator','🛗','투명 엘리베이터','층 버튼을 누르고 올라가요','c-mint')}${cat('language','🔤','말글 놀이터','ABC · 한글 · 그림단어','c-yellow')}${cat('think','🧠','생각 놀이터','기억 · 색깔 · 모양','c-lav')}${cat('potty','🚽','화장실 탐험대','직접 눌러 순서대로 해봐요','c-peach')}${cat('music','🎵','음악 놀이터','내가 고르는 동요와 음악','c-pink')}${cat('together','👨‍👩‍👦','엄마아빠랑 같이','화면 밖에서 같이 놀자','c-sky')}</div>`}
function renderNumbers(){main.innerHTML=subhead('🔢 숫자 놀이터','숫자를 좋아하는 서우를 위한 공간')+`<div class="tile-grid">${tile('numberBoard','🚂','1~100 숫자 기차','숫자를 누르면 읽어줘요')}${tile('elevator','🛗','엘리베이터 층놀이','1~20층을 직접 눌러봐요')}${tile('quantity','🍎','몇 개 있을까?','수량과 숫자를 연결해요')}${tile('finger','🖐️','손가락 숫자','자연스러운 손 모양 1~10')}${tile('numberOrder','🧩','숫자 순서 퍼즐','다음 숫자를 찾아봐요')}</div><div class="warning-note">숫자를 외워 세는 것과 실제 수량을 이해하는 것은 다른 경험이에요. 숫자판·수량·손가락·엘리베이터를 다양하게 섞어 놀아보세요.</div>`}
function renderNumberBoard(){main.innerHTML=subhead('🚂 1~100 숫자 기차','좋아하는 숫자를 마음껏 눌러봐')+`<div class="game-card"><div class="prompt"><span class="eyebrow">숫자</span><h2 id="numHero">1</h2><p id="numSpeech">${esc(numberSpeech(1))}</p></div><div class="number-board" style="margin-top:14px">${Array.from({length:100},(_,i)=>`<button class="number-btn" data-num="${i+1}">${i+1}</button>`).join('')}</div></div>`;main.querySelectorAll('[data-num]').forEach(b=>b.onclick=()=>{const n=+b.dataset.num;document.querySelector('#numHero').textContent=n;document.querySelector('#numSpeech').textContent=numberSpeech(n);audio.speak(numberSpeech(n));b.animate?.([{transform:'scale(1)'},{transform:'scale(1.16)'},{transform:'scale(1)'}],{duration:260})})}
function handSvg(count,side='left'){const active=Math.max(0,Math.min(5,count));const xs=[35,58,82,106],heights=[62,78,84,68];let fingers=xs.map((x,i)=>{const on=i<Math.min(active,4);const h=on?heights[i]:24;const y=96-h;return`<rect x="${x}" y="${y}" width="18" height="${h}" rx="9" class="skin ${on?'raised':'curled'}"/><path d="M${x+4} ${y+8} Q${x+9} ${y+4} ${x+14} ${y+8}" class="nail"/>`}).join('');const thumbOn=active===5;const thumb=`<g class="${thumbOn?'':'thumb-curled'}"><rect x="12" y="83" width="22" height="58" rx="11" class="skin" transform="rotate(-42 23 112)"/><path d="M14 88 Q22 82 29 89" class="nail"/></g>`;return`<svg class="hand-svg ${side}" viewBox="0 0 160 190" aria-label="손가락 ${active}개"><rect x="42" y="89" width="88" height="82" rx="32" class="skin palm-svg"/><rect x="63" y="150" width="47" height="36" rx="16" class="skin wrist-svg"/>${fingers}${thumb}<path d="M48 150 Q82 165 123 146" class="palm-line"/></svg>`}
function fingerHands(n){return`<div class="natural-hands">${handSvg(Math.min(5,n),'left')}${n>5?handSvg(n-5,'right'):''}</div>`}
function startFinger(root){const s={q:0,score:0,tries:0,total:6};function draw(){s.locked=false;if(s.q>=s.total){complete('finger',{score:s.score});confetti();audio.success();root.innerHTML=`<div class="result"><div class="big">🙌</div><h2>손가락 숫자 성공!</h2><p>별을 ${s.score}개 모았어!</p><div class="btns"><button id="fingerAgain" class="btn primary">한 번 더</button><button data-go="numbers" class="btn soft">숫자 놀이터</button></div></div>`;document.querySelector('#fingerAgain').onclick=()=>{s.q=0;s.score=0;draw()};wireGo();return}const level=difficultyLevel('finger'),max=level===1?5:10,n=1+rand(max);let vals=new Set([n]);while(vals.size<3)vals.add(1+rand(max));const opts=shuffle([...vals]);root.innerHTML=`<div class="game-top"><button class="back-btn" data-go="numbers">←</button><div class="progress"><i style="width:${s.q/s.total*100}%"></i></div><div class="stars">⭐ ${s.score}</div></div><div class="game-card prompt"><span class="eyebrow">손가락</span><h2>몇 개 올라갔을까?</h2>${fingerHands(n)}<p>손 모양을 천천히 살펴봐</p></div><div class="choices">${opts.map(v=>`<button class="choice" data-fn="${v}">${v}</button>`).join('')}</div><div class="feedback" id="fingerFeedback">서우 손으로도 똑같이 만들어봐 😊</div>`;audio.speak('손가락이 몇 개 올라갔을까?');wireGo();root.querySelectorAll('[data-fn]').forEach(b=>b.onclick=()=>{if(s.locked)return;s.tries++;const ok=+b.dataset.fn===n;recordChoice(ok,ok&&s.tries===1);if(ok){s.locked=true;b.classList.add('good');document.querySelector('#fingerFeedback').textContent=`${numberSpeech(n)}개! 서우 손으로도 해볼까?`;audio.success();const praise=audio.speak(`${numberSpeech(n)}개! 잘했어!`);s.score++;s.q++;s.tries=0;later(()=>{const epoch=routeEpoch;praise.then(()=>{if(epoch===routeEpoch)draw()})},1100)}else{document.querySelector('#fingerFeedback').textContent='괜찮아. 손가락을 하나씩 세어볼까?';audio.speak('괜찮아. 하나씩 세어볼까?')}})}draw()}
function renderElevator(){
  const current=window.SeowooElevator.current;
  main.innerHTML=subhead('🛗 투명 엘리베이터','가고 싶은 층을 누르고 바깥 풍경을 구경해요')+`<div class="elevator-shell"><div class="elevator-display" aria-label="현재 층"><span id="elevatorArrow">•</span><strong id="elevatorFloor">${current}</strong><small>F</small></div><button id="elevatorFullscreen" class="fullscreen-control" aria-label="전체 화면 전환"><svg aria-hidden="true" viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/></svg></button><div class="glass-cabin"><div class="outside-view" aria-hidden="true"></div><div class="cabin-frame"><div class="rail left"></div><div class="rail right"></div><div class="door door-l"></div><div class="door door-r"></div><div class="cabin-label">SEOWOO · SKY GARDEN</div></div></div><div id="elevatorMsg" class="elevator-msg" role="status">${current}층이에요. 어디로 갈까?</div><div class="floor-panel" role="group" aria-label="가고 싶은 층 선택">${Array.from({length:20},(_,i)=>20-i).map(f=>`<button class="floor-key" data-floor="${f}" aria-label="${f}층" aria-pressed="false">${f}</button>`).join('')}</div></div>`;
  const full=main.querySelector('#elevatorFullscreen');full.hidden=matchMedia('(display-mode: standalone)').matches||!document.documentElement.requestFullscreen;full.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen({navigationUI:'hide'})}catch{toast('이 화면 크기로 계속 놀 수 있어요')}};window.SeowooElevator.mount(main.querySelector('.elevator-shell'));
}
function renderLanguage(){main.innerHTML=subhead('🔤 말글 놀이터','노래처럼 듣고, 그림처럼 만나봐')+`<div class="tile-grid">${tile('alphabet','🔠','ABC 카드','A부터 Z까지 그림과 함께')}${tile('englishWords','🐶','그림 영단어','80개가 넘는 그림 단어')}${tile('koreanWords','🍎','그림 한글단어','그림을 누르면 한글이 짠!')}${tile('hangul','🎶','가나다 리듬','느린 리듬으로 따라 말해요')}</div>`}
function renderAlphabet(){main.innerHTML=subhead('🔠 ABC 카드','카드를 누르면 영어로 읽어줘요')+`<div class="alpha-grid">${C.alphabet.map(x=>`<button class="alpha-card" data-alpha="${x[0]}"><b>${x[0]}</b><div style="font-size:34px">${x[2]}</div><small>${x[1]}</small></button>`).join('')}</div><div class="controls"><button id="abcSong" class="btn primary">▶ ABC 리듬 따라가기</button></div>`;main.querySelectorAll('[data-alpha]').forEach(b=>b.onclick=()=>{const x=C.alphabet.find(v=>v[0]===b.dataset.alpha);audio.speak(`${x[0]}. ${x[1]}`,'en-US',.78)});document.querySelector('#abcSong').onclick=()=>playSequence(C.alphabet.map(x=>x[0]),'en-US',520)}
function renderWords(mode){const isEn=mode==='en',cats=['전체',...new Set(C.words.map(w=>w.cat))],active=wordFilter[mode]||'전체',list=active==='전체'?C.words:C.words.filter(w=>w.cat===active);main.innerHTML=subhead(isEn?'🐶 그림 영단어':'🍎 그림 한글단어',isEn?`${C.words.length}개 그림을 누르고 영어를 들어요`:`${C.words.length}개 그림을 누르면 한글이 나타나요`)+`<div class="category-chips">${cats.map(c=>`<button class="filter-chip ${c===active?'on':''}" data-wordcat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="word-grid">${list.map(w=>{const i=C.words.indexOf(w);return`<button class="word-card" data-word="${i}"><div class="pic">${w.pic}</div><b>${isEn?esc(w.en):'?'}</b><small>${isEn?esc(w.ko):'그림을 눌러봐'}</small></button>`}).join('')}</div>`;main.querySelectorAll('[data-wordcat]').forEach(b=>b.onclick=()=>{wordFilter[mode]=b.dataset.wordcat;renderWords(mode);wireGo()});main.querySelectorAll('[data-word]').forEach(b=>b.onclick=async()=>{const w=C.words[+b.dataset.word];if(isEn){audio.speak(w.en,'en-US',.9,w.englishAudio?{text:w.en,src:w.englishAudio}:undefined);b.querySelector('small').textContent=w.ko}else{b.querySelector('b').textContent=w.ko;b.querySelector('small').textContent=w.sound||w.en;audio.speak(w.ko,'ko-KR',.9,w.koreanAudio?{text:w.ko,src:w.koreanAudio}:undefined)}})}
function renderHangul(){main.innerHTML=subhead('🎶 가나다 리듬','천천히 듣고 같이 따라 말해봐')+`<div class="game-card"><div class="prompt"><span class="eyebrow">한글 리듬</span><h2>가 · 나 · 다 · 라</h2><p>글자가 빛날 때 같이 말해봐요</p></div><div class="rhythm-row">${C.hangulRhythm.map((x,i)=>`<button class="rhythm-chip" data-r="${i}">${x}</button>`).join('')}</div><div class="controls"><button id="hangulPlay" class="btn primary">▶ 가나다 따라가기</button></div></div><div class="section-title"><h2>자음 이름도 들어봐요</h2></div><div class="alpha-grid">${C.consonants.map(x=>`<button class="alpha-card" data-con="${x[0]}"><b>${x[0]}</b><small>${x[1]}</small></button>`).join('')}</div>`;main.querySelectorAll('[data-con]').forEach(b=>b.onclick=()=>{const x=C.consonants.find(v=>v[0]===b.dataset.con);audio.speak(x[1])});main.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>audio.speak(C.hangulRhythm[+b.dataset.r]));document.querySelector('#hangulPlay').onclick=()=>playSequence(C.hangulRhythm,'ko-KR',640)}
async function playSequence(items,lang,delay){stopTimers();audio.stopVoice();const epoch=routeEpoch;const chips=[...main.querySelectorAll('.rhythm-chip,.alpha-card')];for(let i=0;i<items.length&&epoch===routeEpoch;i++){chips.forEach(c=>c.classList.remove('on'));chips[i]?.classList.add('on');await audio.speak(items[i],lang,.86);if(epoch!==routeEpoch)break;await new Promise(resolve=>setTimeout(resolve,Math.min(delay,250)))}if(epoch===routeEpoch)chips.forEach(c=>c.classList.remove('on'))}
function renderThink(){main.innerHTML=subhead('🧠 생각 놀이터','짧고 즐겁게 생각하는 힘을 써봐')+`<div class="tile-grid">${tile('memory','🧠','기억하고 톡톡','순서를 잠깐 기억해요')}${tile('color','🌈','색깔 찾아줘','듣고 같은 색을 골라요')}${tile('shape','🔺','같은 모양 찾기','모양을 보고 찾아요')}${tile('quantity','🍎','많고 적게 세기','물체를 하나씩 세어봐요')}</div>`}
function resetPotty(){potty.step=0;potty.kind=null;potty.wash=0;potty.flushing=false}
function pottyPrompt(){const msgs=['문을 열고 화장실에 들어가 볼까?','바지를 천천히 내려볼까?','변기에 앉아볼까?','쉬 또는 응가를 해볼까?','휴지로 깨끗하게 닦아볼까?','레버를 눌러 물을 내려볼까?','바지를 다시 올려볼까?','비누로 손을 깨끗하게 씻어볼까?','모든 순서를 해봤어!'];return msgs[Math.min(potty.step,msgs.length-1)]}
function pottyScene(){const sitting=potty.step>=3&&potty.step<=5,near=potty.step>=1,pantsDown=potty.step>=2&&potty.step<=5,wash=potty.step===7,done=potty.step>=8;const bowl=potty.kind==='poop'?'💩':potty.kind==='pee'?'💧':'';return`<div class="bathroom-scene ${potty.flushing?'flush-now':''}"><div class="bath-wall"><div class="bath-window">☁️</div><div class="bath-picture">🌈</div></div><div class="bath-floor"></div><div class="bath-door ${near?'open':''}">🚪</div><div class="toilet-cartoon"><div class="tank"><button id="flushHandle" class="flush-handle" ${potty.step!==5?'disabled':''}>●</button></div><div class="seat"></div><div class="bowl"><span class="bowl-water">〰️</span><span class="bowl-item">${bowl}</span></div><div class="toilet-base"></div></div><div class="sink-cartoon"><div class="faucet">🚰</div><div class="sink-basin">${wash?'🫧':''}</div><div class="soap">🧼</div></div><div class="potty-kid ${near?'near':''} ${sitting?'sitting':''} ${wash?'washing':''} ${done?'done':''}"><div class="kid-head">🙂</div><div class="kid-body">👕</div><div class="kid-pants ${pantsDown?'down':''}">👖</div><div class="kid-tissue">${potty.step===4?'🧻':''}</div></div>${potty.step===4?'<div class="wipe-motion">🧻</div>':''}${wash?`<div class="wash-bubbles">${'🫧'.repeat(Math.max(1,potty.wash))}</div>`:''}</div>`}
function pottyActions(){if(potty.step===0)return`<button class="potty-action" data-potty="next">🚪 문 열고 들어가기</button>`;if(potty.step===1)return`<button class="potty-action" data-potty="next">👖 바지 내리기</button>`;if(potty.step===2)return`<button class="potty-action" data-potty="next">🚽 변기에 앉기</button>`;if(potty.step===3)return`<button class="potty-action blue" data-potty-kind="pee">💧 쉬 하기</button><button class="potty-action brown" data-potty-kind="poop">💩 응가 하기</button><button class="btn soft" data-potty="skip">안 나와도 괜찮아</button>`;if(potty.step===4)return`<button class="potty-action" data-potty="next">🧻 휴지로 쓱쓱 닦기</button>`;if(potty.step===5)return`<button class="potty-action" data-potty="flush">🚿 레버 눌러 물 내리기</button>`;if(potty.step===6)return`<button class="potty-action" data-potty="next">👖 바지 올리기</button>`;if(potty.step===7)return`<button class="potty-action" data-potty="wash">🧼 손 비비기 ${potty.wash}/3</button>`;return`<button class="potty-action" data-potty="restart">🔁 다시 해보기</button><button class="btn primary" id="realPotty">🚽 진짜 화장실에 가볼래요</button>`}
function renderPotty(){main.innerHTML=subhead('🚽 화장실 탐험대','캐릭터와 함께 직접 눌러 순서대로 해봐요')+`<div class="potty-progress">${Array.from({length:8},(_,i)=>`<i class="${i<potty.step?'done':''} ${i===potty.step?'now':''}"></i>`).join('')}</div>${pottyScene()}<div class="potty-guide"><h2>${pottyPrompt()}</h2><p>${potty.step===3?'쉬나 응가가 안 나와도 괜찮아. 그냥 앉아본 것도 정말 멋져!':'큰 버튼을 눌러 다음 행동을 해봐.'}</p></div><div class="potty-actions">${pottyActions()}</div><div class="warning-note">배변 성공을 강요하지 않아요. 화장실에 가기·변기에 앉기·순서를 익히는 과정을 칭찬해 주세요.</div>`;wirePotty();if(potty.step<8)audio.speak(pottyPrompt());else{confetti();audio.success();audio.speak('화장실 순서를 모두 해봤어! 정말 멋져!')}}
function wirePotty(){wireGo();main.querySelectorAll('[data-potty-kind]').forEach(b=>b.onclick=()=>{potty.kind=b.dataset.pottyKind;potty.step=4;renderPotty()});main.querySelectorAll('[data-potty]').forEach(b=>b.onclick=()=>{const a=b.dataset.potty;if(a==='next'){potty.step++;renderPotty()}else if(a==='skip'){potty.kind=null;potty.step=4;renderPotty()}else if(a==='flush'){if(potty.flushing)return;potty.flushing=true;renderPotty();audio.tone?.(250,.2,'sine',.04);later(()=>{potty.flushing=false;potty.kind=null;potty.step=6;renderPotty()},1000)}else if(a==='wash'){potty.wash++;audio.tone?.(520,.08);if(potty.wash>=3){potty.step=8;const s=awardSticker();state.stats.rounds++;state.stats.byGame.potty=(state.stats.byGame.potty||0)+1;state.recent.unshift({game:'potty',at:Date.now()});save();renderPotty();if(s)toast(`${s[2]} ${s[1]} 스티커를 받았어!`)}else renderPotty()}else if(a==='restart'){resetPotty();renderPotty()}});document.querySelector('#realPotty')?.addEventListener('click',renderRealPotty);document.querySelector('#flushHandle')?.addEventListener('click',()=>{if(potty.step===5)main.querySelector('[data-potty="flush"]')?.click()})}
function renderRealPotty(){main.innerHTML=subhead('🚽 화장실 다녀오기','화면을 놓고 실제로 해봐요')+`<div class="mission"><div class="pic">🚽</div><h2>화장실에 다녀오자!</h2><p>엄마아빠 손 잡고 천천히 가요.<br>쉬나 응가가 안 나와도 괜찮아요.</p></div><div class="controls"><button id="satPotty" class="btn primary">변기에 앉아봤어요 ⭐</button><button data-go="potty" class="btn soft">다음에 해볼래요</button></div>`;audio.speak('화장실에 다녀오자! 변기에 잠깐 앉아보기만 해도 멋져!');document.querySelector('#satPotty').onclick=()=>{const s=awardSticker();state.stats.rounds++;save();confetti();audio.success();toast(s?`${s[2]} ${s[1]} 스티커를 받았어!`:'변기에 앉아본 것도 정말 멋져!');setTimeout(()=>go('treasure'),900)};wireGo()}
function renderTogether(){const m=C.missions[Math.floor(Math.random()*C.missions.length)];main.innerHTML=subhead('👨‍👩‍👦 엄마아빠랑 같이','화면 밖에서 말하고 움직여봐요')+`<div class="mission"><div class="pic">${m.pic}</div><h2>${m.text}</h2><p>엄마아빠도 같이 해주세요.<br>30초~2분이면 충분해요!</p></div><div class="controls"><button id="missionSpeak" class="btn soft">🔊 다시 듣기</button><button id="missionDone" class="btn primary">같이 해봤어요! ⭐</button><button id="missionNext" class="btn yellow">다른 미션</button></div>`;audio.speak(m.say);document.querySelector('#missionSpeak').onclick=()=>audio.speak(m.say);document.querySelector('#missionNext').onclick=renderTogether;document.querySelector('#missionDone').onclick=()=>{state.stats.rounds++;state.stats.byGame.together=(state.stats.byGame.together||0)+1;state.recent.unshift({game:'together',at:Date.now()});const s=awardSticker();save();confetti();toast(s?`${s[2]} 스티커를 받았어!`:'같이 놀아서 더 즐거웠어!');setTimeout(renderTogether,700)}}
function renderMusic(){main.innerHTML=subhead('🎵 음악 놀이터','엄마아빠가 음원을 추가하면 여기서 골라 들어요')+`<div class="music-grid">${C.music.filter(x=>x.enabled).map((m,i)=>`<div class="music-card"><div class="cover">${m.cover}</div><div><b>${esc(m.title)}</b><small>${esc(m.category)} · ${m.file?'재생 가능':'음원 추가 예정'}</small></div><button class="play" data-music="${i}">${m.file?'▶':'＋'}</button></div>`).join('')}</div><div class="warning-note">저작권 음원을 임의로 넣지 않았어요. <b>data/content.js</b>의 music 항목에 파일 경로를 적고 음원을 <b>/audio</b>에 추가하면 자동으로 재생됩니다.</div>`;main.querySelectorAll('[data-music]').forEach(b=>b.onclick=async()=>{const m=C.music.filter(x=>x.enabled)[+b.dataset.music];if(!m.file){toast('엄마아빠가 음원을 추가하면 들을 수 있어요 🎵');return}const ok=await audio.playMusic(m.file);if(!ok)toast('음원 파일을 확인해 주세요')})}
function renderTreasure(){main.innerHTML=subhead('🏆 서우의 보물상자',`모은 스티커 ${state.stickers.length}개`)+`<div class="sticker-grid">${C.stickers.map(s=>{const on=state.stickers.includes(s[0]);return`<div class="sticker ${on?'':'locked'}"><div><div class="pic">${on?s[2]:'❓'}</div><small>${on?s[1]:'아직 비밀'}</small></div></div>`}).join('')}</div><div class="warning-note">스티커는 경쟁 점수가 아니에요. 놀이와 새로운 생활습관을 시도한 과정을 축하하는 작은 보상이에요.</div>`}
function renderParentGate(){let seq=[1,2,3],pos=0;main.innerHTML=subhead('👨‍👩‍👦 보호자 메뉴')+`<div class="gate"><div style="font-size:52px">🔒</div><h2>보호자 확인</h2><p class="helper">아이가 실수로 설정을 바꾸지 않도록<br><b>1 → 2 → 3</b> 순서로 눌러주세요.</p><div class="gate-grid">${[2,1,3].map(n=>`<button data-gate="${n}">${n}</button>`).join('')}</div></div>`;main.querySelectorAll('[data-gate]').forEach(b=>b.onclick=()=>{const n=+b.dataset.gate;if(n===seq[pos]){pos++;b.style.background='#DFF7E7';if(pos===3)renderParent()}else{pos=0;toast('1부터 다시 눌러주세요')}})}
function renderParent(){const pct=state.stats.totalChoices?Math.round(state.stats.correct/state.stats.totalChoices*100):0;main.innerHTML=subhead('👨‍👩‍👦 보호자 메뉴','발달검사가 아닌 놀이 기록과 설정입니다')+`<div class="parent-card"><h2>놀이 기록</h2><div class="stats"><div class="stat"><b>${state.stats.rounds}회</b><small>완료한 놀이/활동</small></div><div class="stat"><b>${state.stats.firstTry}⭐</b><small>첫 시도 성공</small></div><div class="stat"><b>${pct}%</b><small>선택형 놀이 정답 비율</small></div><div class="stat"><b>${state.stickers.length}개</b><small>모은 스티커</small></div></div><p class="helper">이 숫자들은 앱 안에서의 놀이 기록일 뿐, 발달 수준이나 또래 비교를 의미하지 않습니다.</p></div><div class="parent-card"><h2>부모 설정</h2>${toggleRow('voice','음성 안내','놀이 안내와 숫자 읽기를 들어요')}${toggleRow('sound','효과음','성공음과 버튼음을 사용해요')}<label class="setting"><b>목소리 크기</b><input id="voiceVolume" type="range" min="0" max="1" step="0.05" value="${audio.voiceVolume}"></label><label class="setting"><b>효과음 크기</b><input id="sfxVolume" type="range" min="0" max="1" step="0.05" value="${audio.sfxVolume}"></label><div class="setting"><span><b>난이도</b><small>자동 또는 1~3단계 고정</small></span><select id="difficulty"><option value="auto">자동</option><option value="1">1단계</option><option value="2">2단계</option><option value="3">3단계</option></select></div><div class="setting"><span><b>숫자 읽기</b><small>하나/일 방식 선택</small></span><select id="countMode"><option value="both">둘 다</option><option value="native">하나·둘</option><option value="sino">일·이</option></select></div><div class="setting"><span><b>쉬기 안내</b><small>연속 사용 후 휴식 알림</small></span><select id="breakMinutes"><option value="10">10분</option><option value="15">15분</option><option value="20">20분</option><option value="30">30분</option></select></div></div><div class="parent-card"><h3>기록 관리</h3><button id="resetData" class="btn soft">이 기기의 놀이 기록 초기화</button></div>`;['voiceVolume','sfxVolume'].forEach(id=>{const el=document.getElementById(id);el.oninput=()=>{audio[id==='voiceVolume'?'setVoiceVolume':'setSfxVolume'](+el.value);save()}});['difficulty','countMode','breakMinutes'].forEach(id=>{const el=document.querySelector('#'+id);el.value=String(state.settings[id]);el.onchange=()=>setting(id,id==='breakMinutes'?+el.value:el.value)});main.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;setting(k,!state.settings[k]);audio.stopAll();renderParent()});document.querySelector('#resetData').onclick=()=>{if(confirm('이 기기의 놀이 기록과 설정을 모두 초기화할까요?'))reset()}}
function toggleRow(k,t,s){return`<div class="setting"><span><b>${t}</b><small>${s}</small></span><button class="toggle ${state.settings[k]?'on':''}" data-toggle="${k}" aria-label="${t}"><i></i></button></div>`}
function updateHeader(){document.querySelectorAll('#bottomNav [data-go]').forEach(b=>{if(b.dataset.go===route)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.querySelector('#soundBtn').textContent=state.settings.voice?'🔊':'🔇'}
function setupHeader(){document.querySelector('#parentBtn').onclick=()=>go('parent');document.querySelector('#soundBtn').onclick=()=>{setting('voice',!state.settings.voice);audio.stopVoice();updateHeader();toast(state.settings.voice?'음성 안내를 켰어요':'음성 안내를 껐어요')};document.querySelectorAll('.brand,[data-go]').forEach(b=>{if(b.dataset.go)b.onclick=()=>go(b.dataset.go)});document.querySelectorAll('#bottomNav [data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function setupBreak(){const dlg=document.querySelector('#breakDialog');let active=0,last=Date.now();document.querySelector('#breakDone').onclick=()=>{dlg.close();active=0;last=Date.now()};setInterval(()=>{const now=Date.now();if(!document.hidden&&!dlg.open)active+=Math.min(now-last,30000);last=now;if(active>(state.settings.breakMinutes||15)*60000&&!dlg.open&&!document.hidden){audio.stopAll();dlg.showModal()}},10000)}
function init(){setupHeader();setupBreak();state.stats.sessionStarts=(state.stats.sessionStarts||0)+1;save();resetPotty();let resume='home';try{resume=sessionStorage.getItem('seowoo-route')||'home'}catch{}go(resume)}
window.SeowooApp={go};document.addEventListener('pointerdown',()=>audio.unlock(),{once:true});document.addEventListener('DOMContentLoaded',init);
})();