(()=>{'use strict';
const K=window.SeowooCore;if(!K||!window.SeowooApp)return;
const {C,audio,recordChoice,complete,difficultyLevel,shuffle,numberSpeech,confetti,toast}=K;
const main=document.querySelector('#main');const originalGo=window.SeowooApp.go.bind(window.SeowooApp);
let pottyStep=0,pottyResult='';let elevatorFloor=1,elevatorMoving=false;let fingerQ=0,fingerScore=0,fingerTries=0;const FINGER_TOTAL=6;

function header(title,sub,back='home'){return`<div class="subhead v4-sub"><button class="back-btn" data-v4-back="${back}" aria-label="뒤로">←</button><div><h1>${title}</h1><small>${sub||''}</small></div></div>`}
function wireBack(){main.querySelectorAll('[data-v4-back]').forEach(b=>b.onclick=()=>originalGo(b.dataset.v4Back||'home'))}
function speak(t,lang='ko-KR',rate=.9){audio.speak(t,lang,rate)}
function softSuccess(t){audio.success();speak(t);confetti()}

const pottySteps=[
 ['화장실로 가기','문을 톡 누르고 변기 앞으로 가볼까?','🚪'],['바지 내리기','파란 바지를 아래로 내려줘.','👖'],['변기에 앉기','변기를 톡 눌러서 앉아보자.','🚽'],['쉬 또는 응가하기','쉬할까? 응가할까? 골라봐.','💧'],['깨끗하게 닦기','휴지를 톡 눌러서 닦아줘.','🧻'],['물 내리기','물내림 버튼을 눌러볼까?','🔘'],['바지 올리기','바지를 다시 올려줘.','👖'],['손 씻기','세면대를 톡 누르고 손을 씻자.','🧼']
];
function pottyClass(){return`step-${Math.min(pottyStep,7)} ${pottyResult==='pee'?'did-pee':''} ${pottyResult==='poop'?'did-poop':''}`}
function renderPottyV4(){if(pottyStep>7){renderPottyDone();return}const[title,desc,ico]=pottySteps[pottyStep];main.innerHTML=header('🚽 화장실 탐험대','곰돌이를 직접 도와주며 순서대로 해봐요')+`<section class="potty-play-card"><div class="potty-progress">${pottySteps.map((_,i)=>`<i class="${i<pottyStep?'done':i===pottyStep?'now':''}">${i+1}</i>`).join('')}</div><div class="potty-instruction"><span>${ico}</span><div><b>${title}</b><small>${desc}</small></div></div><div class="bathroom ${pottyClass()}" id="bathroom"><button class="bath-door potty-object" data-potty-act="door" aria-label="화장실 문"><span>🚪</span></button><div class="bath-wall"><span class="tile t1"></span><span class="tile t2"></span><span class="tile t3"></span></div><div class="potty-kid" id="pottyKid"><div class="kid-head">🐻</div><div class="kid-body"></div><div class="kid-pants">👖</div><div class="kid-arm arm-l"></div><div class="kid-arm arm-r"></div></div><button class="toilet potty-object" data-potty-act="toilet" aria-label="변기"><span class="tank"></span><span class="flush">●</span><span class="seat"></span><span class="bowl"><i class="pee">💧</i><i class="poop">💩</i><i class="swirl">🌀</i></span></button><button class="paper potty-object" data-potty-act="paper" aria-label="휴지">🧻</button><button class="sink potty-object" data-potty-act="sink" aria-label="세면대"><span>🚰</span><i>🫧</i></button><div class="bath-mat">⭐</div></div><div class="potty-actions">${pottyActionButtons()}</div></section><div class="warning-note">쉬나 응가가 바로 나오지 않아도 괜찮아요. 실제 화장실에서도 <b>가보기 → 앉아보기 → 손 씻기</b> 과정을 편안하게 반복해 주세요.</div>`;wireBack();bindPotty();speak(`${title}. ${desc}`)}
function pottyActionButtons(){if(pottyStep===3)return`<button class="btn potty-choice pee-btn" data-potty-result="pee">💧 쉬할래요</button><button class="btn potty-choice poop-btn" data-potty-result="poop">💩 응가할래요</button>`;const labels=['🚪 화장실로 가기','👖 바지 내리기','🚽 변기에 앉기','','🧻 휴지로 닦기','💦 물 내리기','👖 바지 올리기','🧼 손 씻기'];return`<button class="btn primary potty-main-action" data-potty-next>${labels[pottyStep]}</button>`}
function bindPotty(){const expected=['door','pants','toilet','choose','paper','flush','pants','sink'][pottyStep];main.querySelector('[data-potty-next]')?.addEventListener('click',()=>advancePotty());main.querySelectorAll('[data-potty-result]').forEach(b=>b.onclick=()=>{pottyResult=b.dataset.pottyResult;speak(pottyResult==='pee'?'쉬를 했어요. 잘했어!':'응가를 했어요. 잘했어!');const bath=main.querySelector('#bathroom');bath.classList.toggle('did-pee',pottyResult==='pee');bath.classList.toggle('did-poop',pottyResult==='poop');setTimeout(()=>{pottyStep++;renderPottyV4()},850)});main.querySelectorAll('[data-potty-act]').forEach(el=>el.onclick=()=>{const act=el.dataset.pottyAct;if((expected==='pants'&&act==='pants')||act===expected)advancePotty();else if(expected==='flush'&&act==='toilet')advancePotty();else if(expected==='choose')speak('쉬할지 응가할지 아래에서 골라봐!');else speak('지금은 반짝이는 순서대로 해볼까?')});const pants=main.querySelector('.kid-pants');if(pants)pants.onclick=()=>{if(expected==='pants')advancePotty();else speak('지금 할 일을 먼저 해볼까?')}}
function advancePotty(){const bath=main.querySelector('#bathroom');if(!bath)return;const current=pottyStep;if(current===0){bath.classList.add('walk');speak('화장실로 가요!');setTimeout(next,800);return}if(current===1){bath.classList.add('pants-down');speak('바지를 천천히 내려요.');setTimeout(next,650);return}if(current===2){bath.classList.add('sit');speak('변기에 편하게 앉았어요!');setTimeout(next,700);return}if(current===4){bath.classList.add('wipe');speak('휴지로 깨끗하게 닦아요.');setTimeout(next,750);return}if(current===5){bath.classList.add('flushing');audio.tone?.(430,.12,'sine',.05);setTimeout(()=>audio.tone?.(560,.16,'sine',.05),120);speak('물을 쏴아 내려요!');setTimeout(()=>{pottyResult='';next()},950);return}if(current===6){bath.classList.add('pants-up');speak('바지를 다시 올려요.');setTimeout(next,600);return}if(current===7){bath.classList.add('washing');speak('비누로 손을 깨끗하게 씻어요.');setTimeout(next,1100);return}function next(){pottyStep++;renderPottyV4()}}
function renderPottyDone(){main.innerHTML=header('🚽 화장실 탐험대','모든 순서를 다 해봤어요!')+`<div class="potty-finish"><div class="finish-bear">🐻✨</div><h2>화장실 탐험 성공!</h2><p>화장실에 가고, 변기에 앉고, 닦고, 물도 내리고, 손도 씻었어.</p><div class="controls"><button id="pottyAgain" class="btn primary">한 번 더 해볼래요</button><button id="realTry" class="btn yellow">🚽 진짜 화장실 가보기</button></div></div>`;wireBack();softSuccess('서우야, 화장실 순서를 모두 해봤네! 정말 멋져!');document.querySelector('#pottyAgain').onclick=()=>{pottyStep=0;pottyResult='';renderPottyV4()};document.querySelector('#realTry').onclick=()=>{toast('엄마아빠와 진짜 화장실에 가서 변기에 잠깐 앉아봐요 ⭐');speak('이번에는 엄마아빠랑 진짜 화장실에 가볼까?')}}

function floorScenery(f){if(f<=3)return'🌳 🚗 🌳 🏠';if(f<=7)return'🏢 🌳 🚌 🏫';if(f<=12)return'🏢 🏢 ☁️ 🐦';if(f<=16)return'☁️ 🐦 ☁️ ✈️';return'☁️ ☀️ ☁️ ✨'}
function elevatorTrack(){return Array.from({length:20},(_,i)=>20-i).map(f=>`<div class="floor-band" data-band="${f}"><b>${f}F</b><span>${floorScenery(f)}</span><i></i></div>`).join('')}
function floorTranslate(f){const bandH=170,viewport=330;const y=(20-f)*bandH;return viewport/2-(y+bandH/2)}
function renderElevator(){main.innerHTML=header('🛗 투명 엘리베이터','층 버튼을 누르면 창밖 풍경이 움직여요','numbers')+`<section class="elevator-shell"><div class="elevator-panel"><div class="floor-display"><span id="elevatorArrow">•</span><b id="elevatorFloor">${elevatorFloor}</b><small>F</small></div><div id="elevatorMessage">원하는 층을 눌러봐!</div></div><div class="glass-elevator" id="glassElevator"><div class="outside-track" id="outsideTrack" style="transform:translateY(${floorTranslate(elevatorFloor)}px)">${elevatorTrack()}</div><div class="glass-glow"></div><div class="rail rail-l"></div><div class="rail rail-r"></div><div class="door door-l"></div><div class="door door-r"></div><div class="cabin-floor"><span>👟</span><span>⭐</span></div></div><div class="floor-buttons">${Array.from({length:20},(_,i)=>i+1).map(f=>`<button class="floor-button ${f===elevatorFloor?'here':''}" data-floor="${f}">${f}</button>`).join('')}</div><div class="elevator-mini-controls"><button id="doorOpen" class="mini-e-btn">◀ ▶<small>열림</small></button><button id="doorClose" class="mini-e-btn">▶ ◀<small>닫힘</small></button></div></section>`;wireBack();bindElevator();speak(`${elevatorFloor}층이에요. 가고 싶은 층 버튼을 눌러볼까?`)}
function bindElevator(){main.querySelectorAll('[data-floor]').forEach(b=>b.onclick=()=>moveElevator(+b.dataset.floor));document.querySelector('#doorOpen').onclick=()=>{if(elevatorMoving)return;document.querySelector('#glassElevator').classList.remove('doors-closed');speak('문이 열립니다')};document.querySelector('#doorClose').onclick=()=>{if(elevatorMoving)return;document.querySelector('#glassElevator').classList.add('doors-closed');speak('문이 닫힙니다')}}
function moveElevator(target){if(elevatorMoving)return;if(target===elevatorFloor){audio.tone?.(840,.12);speak(`지금 ${target}층이에요`);return}elevatorMoving=true;const start=elevatorFloor,dir=target>start?1:-1,diff=Math.abs(target-start),duration=Math.min(6200,900+diff*330);const glass=document.querySelector('#glassElevator'),track=document.querySelector('#outsideTrack'),disp=document.querySelector('#elevatorFloor'),arrow=document.querySelector('#elevatorArrow'),msg=document.querySelector('#elevatorMessage');glass.classList.add('moving','doors-closed');arrow.textContent=dir>0?'▲':'▼';msg.textContent=dir>0?'올라가는 중이에요…':'내려가는 중이에요…';main.querySelectorAll('[data-floor]').forEach(b=>b.disabled=true);setTimeout(()=>{track.style.transitionDuration=duration+'ms';track.style.transform=`translateY(${floorTranslate(target)}px)`},240);let cur=start;const stepTime=Math.max(250,duration/diff);const timer=setInterval(()=>{cur+=dir;if((dir>0&&cur>=target)||(dir<0&&cur<=target))cur=target;disp.textContent=cur;audio.tone?.(520,.045,'sine',.025);if(cur===target)clearInterval(timer)},stepTime);setTimeout(()=>{clearInterval(timer);elevatorFloor=target;disp.textContent=target;arrow.textContent='•';msg.textContent=`${target}층입니다. 문이 열려요!`;glass.classList.remove('moving');setTimeout(()=>glass.classList.remove('doors-closed'),220);main.querySelectorAll('[data-floor]').forEach(b=>{b.disabled=false;b.classList.toggle('here',+b.dataset.floor===target)});audio.tone?.(920,.18,'sine',.07);speak(`${target}층입니다`);elevatorMoving=false},duration+300)}

function handSVG(count,mirror=false){const active={index:count>=1,middle:count>=2,ring:count>=3,pinky:count>=4,thumb:count>=5};const finger=(name,x,y,w,h,rx=10)=>active[name]?`<rect class="v4-finger-up" x="${x}" y="${y}" width="${w}" height="${h}" rx="${rx}"/>`:`<ellipse class="v4-knuckle" cx="${x+w/2}" cy="103" rx="${w/2}" ry="11"/>`;return`<svg class="real-hand ${mirror?'mirror':''}" viewBox="0 0 170 210" role="img" aria-label="손가락 ${count}개"><g><rect class="wrist" x="64" y="158" width="48" height="47" rx="16"/><path class="palm-shape" d="M45 94 C47 77 59 70 76 72 L118 76 C134 78 142 91 139 111 L132 157 C129 176 115 184 94 184 L73 183 C53 182 40 169 40 149 Z"/>${finger('index',58,37,20,75)}${finger('middle',81,24,21,88)}${finger('ring',105,35,20,77)}${finger('pinky',129,55,18,60)}${active.thumb?`<rect class="v4-thumb-up" x="26" y="99" width="22" height="64" rx="11" transform="rotate(-38 37 131)"/>`:`<ellipse class="v4-knuckle thumb-k" cx="45" cy="135" rx="13" ry="10" transform="rotate(-28 45 135)"/>`}<path class="palm-line" d="M58 138 Q87 118 119 133"/><path class="palm-line" d="M68 154 Q88 143 111 151"/></g></svg>`}
function renderFingerV4(resetRound=false){if(resetRound){fingerQ=0;fingerScore=0;fingerTries=0}if(fingerQ>=FINGER_TOTAL){complete('finger',{score:fingerScore});softSuccess('손가락 숫자를 정말 잘 봤어!');main.innerHTML=header('✋ 손가락 숫자','자연스러운 손 모양으로 1부터 10까지')+`<div class="result"><div class="big">🙌</div><h2>손가락 박사!</h2><p>별을 ${fingerScore}개 모았어.</p><div class="controls"><button id="fingerAgain" class="btn primary">한 번 더</button><button class="btn soft" data-v4-back="numbers">숫자 놀이터</button></div></div>`;wireBack();document.querySelector('#fingerAgain').onclick=()=>renderFingerV4(true);return}const level=difficultyLevel('finger'),max=level===1?5:10,n=1+Math.floor(Math.random()*max);let vals=new Set([n]);while(vals.size<3)vals.add(1+Math.floor(Math.random()*max));const opts=shuffle([...vals]);fingerTries=0;const handView=n<=5?handSVG(n):handSVG(5)+handSVG(n-5,true);main.innerHTML=header('✋ 손가락 숫자','손 모양을 보고 몇 개인지 맞혀봐요','numbers')+`<div class="game-top"><div></div><div class="progress"><i style="width:${fingerQ/FINGER_TOTAL*100}%"></i></div><div class="stars">⭐ ${fingerScore}</div></div><div class="game-card prompt"><span class="eyebrow">손가락</span><h2>몇 개 올라갔을까?</h2><div class="v4-hand-wrap">${handView}</div></div><div class="choices">${opts.map(v=>`<button class="choice v4-number-choice" data-finger-answer="${v}">${v}</button>`).join('')}</div><div id="fingerFeedback" class="feedback">서우 손가락으로도 같이 만들어봐 ✋</div>`;wireBack();speak('손가락이 몇 개 올라갔을까?');main.querySelectorAll('[data-finger-answer]').forEach(b=>b.onclick=()=>{fingerTries++;const ok=+b.dataset.fingerAnswer===n;recordChoice(ok,ok&&fingerTries===1);if(ok){b.classList.add('good');fingerScore++;fingerQ++;document.querySelector('#fingerFeedback').textContent=`${numberSpeech(n)}개! 잘했어!`;audio.success();speak(`${numberSpeech(n)}개! 잘했어!`);setTimeout(()=>renderFingerV4(false),700)}else{document.querySelector('#fingerFeedback').textContent='한 번 더 손가락을 천천히 세어볼까?';if(fingerTries>=2)main.querySelector(`[data-finger-answer="${n}"]`)?.classList.add('hint')}})}

function renderWordBrowser(mode,category='전체'){const isEn=mode==='en',cats=['전체',...new Set(C.words.map(w=>w.cat))];const words=category==='전체'?C.words:C.words.filter(w=>w.cat===category);main.innerHTML=header(isEn?'🐶 그림 영단어':'🍎 그림 한글단어',`${C.words.length}개의 그림단어를 카테고리별로 만나봐요`,'language')+`<div class="word-category-bar">${cats.map(c=>`<button class="word-cat ${c===category?'on':''}" data-word-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="word-count">${esc(category)} · ${words.length}개</div><div class="word-grid v4-word-grid">${words.map(w=>`<button class="word-card v4-word-card" data-v4-word="${C.words.indexOf(w)}"><div class="pic">${w.pic}</div><b>${isEn?esc(w.en):'?'}</b><small>${isEn?esc(w.ko):'그림을 눌러봐'}</small></button>`).join('')}</div>`;wireBack();main.querySelectorAll('[data-word-cat]').forEach(b=>b.onclick=()=>renderWordBrowser(mode,b.dataset.wordCat));main.querySelectorAll('[data-v4-word]').forEach(b=>b.onclick=async()=>{const w=C.words[+b.dataset.v4Word];b.classList.add('spoken');if(isEn){const played=await audio.playFile(w.englishAudio);if(!played)speak(w.en,'en-US',.8);b.querySelector('small').textContent=w.ko}else{b.querySelector('b').textContent=w.ko;b.querySelector('small').textContent=w.sound||w.en;const played=await audio.playFile(w.koreanAudio);if(!played)speak(w.ko)}})}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}

document.addEventListener('click',e=>{const routeEl=e.target.closest('[data-go]');if(!routeEl)return;const r=routeEl.dataset.go;if(r==='potty'||r==='finger'||r==='englishWords'||r==='koreanWords'){e.preventDefault();e.stopImmediatePropagation();audio.unlock();audio.stop();if(r==='potty'){pottyStep=0;pottyResult='';renderPottyV4()}else if(r==='finger')renderFingerV4(true);else renderWordBrowser(r==='englishWords'?'en':'ko')}},true);
document.addEventListener('click',e=>{const b=e.target.closest('[data-v4-route]');if(!b)return;e.preventDefault();e.stopPropagation();if(b.dataset.v4Route==='elevator')renderElevator()},true);
function injectElevatorTile(){const h=[...main.querySelectorAll('.subhead h1')].find(x=>x.textContent.includes('숫자 놀이터'));if(!h)return;const grid=main.querySelector('.tile-grid');if(grid&&!grid.querySelector('[data-v4-route="elevator"]'))grid.insertAdjacentHTML('beforeend',`<button class="tile v4-elevator-tile" data-v4-route="elevator"><span class="emoji">🛗</span><b>투명 엘리베이터</b><small>1~20층 버튼을 누르고 올라가요</small></button>`)}
new MutationObserver(()=>injectElevatorTile()).observe(main,{childList:true,subtree:true});injectElevatorTile();
})();
