(()=>{'use strict';
const IMMERSIVE=new Set(['numberBoard','quantity','numberOrder','finger','elevator','alphabet','englishWords','koreanWords','hangul','color','shape','memory','potty','together']);
const MENU=new Set(['home','numbers','language','think','music','treasure','parent']);
const smoothElevator={current:1,moving:false,raf:0,startTime:0,startFloor:1,targetFloor:1,duration:0,queued:null};
function tryEnterNativeFullscreen(){try{if(document.fullscreenElement)return;const el=document.documentElement;if(el.requestFullscreen){const p=el.requestFullscreen({navigationUI:'hide'});p&&p.catch&&p.catch(()=>{})}}catch(e){}}
function tryExitNativeFullscreen(){try{if(document.fullscreenElement&&document.exitFullscreen){const p=document.exitFullscreen();p&&p.catch&&p.catch(()=>{})}}catch(e){}}
function setMode(dest){const immersive=IMMERSIVE.has(dest);document.body.classList.toggle('game-fullscreen',immersive);document.body.classList.toggle('elevator-fullscreen',dest==='elevator');document.body.dataset.playRoute=dest||'';if(immersive)tryEnterNativeFullscreen();else if(MENU.has(dest))tryExitNativeFullscreen()}
function scenicMarkup(){return`<div class="scenic-world" aria-hidden="true"><div class="scenic-cloud c1"></div><div class="scenic-cloud c2"></div><div class="scenic-cloud c3"></div><div class="scenic-haze"></div><div class="scenic-ridge"></div><div class="scenic-skyline"><div class="scenic-building b1"></div><div class="scenic-building b2"></div><div class="scenic-building b3"></div><div class="scenic-building b4 crown"></div><div class="scenic-building b5"></div><div class="scenic-building b6"></div><div class="scenic-building b7"></div><div class="scenic-building b8"></div></div><div class="scenic-river"></div><div class="scenic-park"></div><div class="scenic-road"></div><div class="scenic-trees">🌳 🌲 🌳 🌲 🌳 🌲 🌳 🌲 🌳</div></div>`}
function trackY(floor){return -(30-floor)*92}
function eased(t){return t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2}
function syncElevatorDom(floorFloat,final=false){const floorEl=document.querySelector('#elevatorFloor'),arrow=document.querySelector('#elevatorArrow'),track=document.querySelector('#floorTrack'),msg=document.querySelector('#elevatorMsg');const shown=Math.max(1,Math.min(20,Math.round(floorFloat)));if(floorEl)floorEl.textContent=shown;if(track){track.style.transition='none';track.style.transform=`translateY(${trackY(floorFloat)}px)`}document.querySelectorAll('.floor-key').forEach(b=>b.classList.toggle('here',+b.dataset.floor===shown));if(arrow)arrow.textContent=smoothElevator.moving?(smoothElevator.targetFloor>smoothElevator.startFloor?'▲':'▼'):'•';if(msg&&smoothElevator.moving&&!final)msg.textContent=`${shown}층을 지나 ${smoothElevator.targetFloor}층으로 가고 있어요 ${smoothElevator.targetFloor>smoothElevator.startFloor?'⬆️':'⬇️'}`}
function finishSmoothElevator(){cancelAnimationFrame(smoothElevator.raf);smoothElevator.raf=0;smoothElevator.current=smoothElevator.targetFloor;smoothElevator.moving=false;syncElevatorDom(smoothElevator.current,true);document.querySelector('.glass-cabin')?.classList.remove('moving');document.querySelector('.cabin-frame')?.classList.remove('doors-closed');const msg=document.querySelector('#elevatorMsg');if(msg)msg.textContent=`딩동! ${smoothElevator.current}층에 도착했어요!`;const K=window.SeowooCore;if(K&&K.audio){K.audio.success();K.audio.speak(`딩동. ${smoothElevator.current}층입니다`)}const queued=smoothElevator.queued;smoothElevator.queued=null;if(queued&&queued!==smoothElevator.current)setTimeout(()=>startSmoothElevator(queued),420)}
function stepSmoothElevator(now){const raw=Math.min(1,(now-smoothElevator.startTime)/smoothElevator.duration);const p=eased(raw);const floor=smoothElevator.startFloor+(smoothElevator.targetFloor-smoothElevator.startFloor)*p;syncElevatorDom(floor,false);if(raw<1){smoothElevator.raf=requestAnimationFrame(stepSmoothElevator)}else finishSmoothElevator()}
function startSmoothElevator(target){target=Math.max(1,Math.min(20,Number(target)||1));if(smoothElevator.moving){smoothElevator.queued=target;return}if(target===smoothElevator.current){const K=window.SeowooCore;if(K&&K.audio){K.audio.success();K.audio.speak(`${target}층이에요`)}return}smoothElevator.startFloor=smoothElevator.current;smoothElevator.targetFloor=target;smoothElevator.moving=true;const distance=Math.abs(target-smoothElevator.startFloor);smoothElevator.duration=Math.min(6200,Math.max(1450,900+distance*285));smoothElevator.startTime=performance.now();document.querySelector('.glass-cabin')?.classList.add('moving');document.querySelector('.cabin-frame')?.classList.add('doors-closed');const msg=document.querySelector('#elevatorMsg');if(msg)msg.textContent=`${target}층으로 출발!`;const K=window.SeowooCore;if(K&&K.audio)K.audio.speak(`${target}층으로 갑니다`);setTimeout(()=>{if(smoothElevator.moving)smoothElevator.raf=requestAnimationFrame(stepSmoothElevator)},340)}
function upgradeElevator(){const track=document.querySelector('#floorTrack');if(!track)return;if(track.dataset.v5!=='1'){track.dataset.v5='1';track.insertAdjacentHTML('afterbegin',scenicMarkup());const cabin=document.querySelector('.glass-cabin');if(cabin)cabin.classList.add('premium-panorama');document.querySelectorAll('.floor-key').forEach(btn=>{btn.setAttribute('aria-label',`${btn.textContent.trim()}층`);btn.title=`${btn.textContent.trim()}층`})}syncElevatorDom(smoothElevator.current,true)}
function detectCurrentScreen(){const main=document.querySelector('#main');if(!main)return;upgradeElevator();if(main.querySelector('.elevator-shell')){setMode('elevator');return}if(main.querySelector('.bathroom-scene')){document.body.classList.add('game-fullscreen');document.body.classList.remove('elevator-fullscreen');return}}
document.addEventListener('click',e=>{const floorBtn=e.target.closest('.floor-key');if(floorBtn&&document.querySelector('.elevator-shell')){e.preventDefault();e.stopImmediatePropagation();startSmoothElevator(+floorBtn.dataset.floor);return}const homeBtn=e.target.closest('#elevatorHome');if(homeBtn&&document.querySelector('.elevator-shell')){e.preventDefault();e.stopImmediatePropagation();startSmoothElevator(1);return}},true);
document.addEventListener('click',e=>{const target=e.target.closest('[data-go]');if(!target)return;const dest=target.dataset.go;if(IMMERSIVE.has(dest)||MENU.has(dest))setMode(dest)},true);
document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&IMMERSIVE.has(document.body.dataset.playRoute||''))document.body.classList.add('game-fullscreen')});
const main=document.querySelector('#main');if(main){new MutationObserver(()=>detectCurrentScreen()).observe(main,{childList:true,subtree:true})}
window.addEventListener('pageshow',detectCurrentScreen);
setTimeout(detectCurrentScreen,0);
})();