(()=>{'use strict';
const K=window.SeowooCore,G=window.SeowooGames;if(!K||!G)return;const{audio,C,recordChoice,complete,confetti,difficultyLevel,shuffle}=K;
let E=0,T=null,S=null;
const cfg=k=>k==='color'?{id:'color',back:'think',title:'🌈 색깔 찾아줘',hint:'같은 색을 톡 눌러줘',pool:C.colors.map(x=>({k:x[0],v:x[1]})),p:x=>`${x.k}을 찾아볼까?`,say:x=>audio.speak(`${x.k}을 찾아볼까?`),o:x=>`<span class="swatch" style="background:${x.v}"></span>`}:k==='shape'?{id:'shape',back:'think',title:'🔺 같은 모양 찾기',hint:'모양을 잘 살펴봐',pool:C.shapes.map(x=>({k:x[0],v:x[1]})),p:x=>`${x.k}을 찾아볼까?`,say:x=>audio.speak(`${x.k}을 찾아볼까?`),o:x=>x.v}:k==='englishFind'?{id:k,back:'language',title:'🔎 영어 찾기',hint:'같은 알파벳을 톡 눌러줘',show:1,pool:C.alphabet.map(x=>({k:x[0]})),p:x=>`${x.k}를 찾아볼까?`,say:x=>audio.speak(x.k,'en-US',.82),o:x=>x.k}:{id:'hangulFind',back:'language',title:'가 한글 찾기',hint:'같은 글자를 톡 눌러줘',show:1,pool:C.hangulRhythm.map(k=>({k})),p:x=>`${x.k}를 찾아볼까?`,say:x=>audio.speak(`${x.k}를 찾아볼까?`),o:x=>x.k};
function stop(){E++;clearTimeout(T);T=null;S=null}
function deck(p,n){const d=[];while(d.length<n){let b=shuffle(p);if(d.length&&b.length>1&&b[0].k===d.at(-1).k){let i=b.findIndex(x=>x.k!==d.at(-1).k);if(i>0)[b[0],b[i]]=[b[i],b[0]]}for(const x of b){d.push(x);if(d.length===n)break}}return d}
function start(k,r=document.querySelector('#main')){if(!r)return;stop();audio.stopVoice?.();let c=cfg(k);S={k,c,q:0,s:0,tr:0,n:12,d:deck(c.pool,12)};draw(r)}
function draw(r){let s=S;if(!s)return;if(s.q>=s.n){complete(s.c.id,{score:s.s,total:s.n});confetti();audio.success();r.innerHTML=`<div class="result"><div class="big">🎉</div><h2>찾기 놀이 끝!</h2><p>12번 끝까지 잘 찾았어. 별을 ${s.s}개 모았어!</p><div class="btns"><button class="btn primary" data-fr="${s.k}">한 번 더</button><button class="btn soft" data-fb="${s.c.back}">다른 놀이</button></div></div>`;return}let t=s.d[s.q],lv=difficultyLevel(s.c.id),n=lv===1?2:lv===2?3:4,os=shuffle([t,...shuffle(s.c.pool.filter(x=>x.k!==t.k)).slice(0,n-1)]);s.tr=0;s.lock=0;r.innerHTML=`<div data-find-screen><div class="game-top"><button class="back-btn" data-fb="${s.c.back}">←</button><div class="progress"><i style="width:${s.q/s.n*100}%"></i></div><div class="stars">⭐ ${s.s}</div></div><div class="section-title"><h2>${s.c.title}</h2></div><div class="game-card prompt">${s.c.show?`<div style="font-size:clamp(64px,16vw,110px);font-weight:900;line-height:1.1;margin:8px">${t.k}</div>`:''}<h2>${s.c.p(t)}</h2><p>${s.c.hint}</p></div><div class="choices">${os.map(x=>`<button class="choice" style="font-size:${s.c.show?'clamp(52px,13vw,88px)':'inherit'};min-height:118px" data-fo="${s.c.pool.indexOf(x)}">${s.c.o(x)}</button>`).join('')}</div><div class="feedback" id="ff">잘 보고 찾아봐</div></div>`;s.c.say(t);r.querySelectorAll('[data-fo]').forEach(b=>b.onclick=()=>ans(r,b,t))}
function ans(r,b,t){let s=S;if(!s||s.lock)return;let x=s.c.pool[+b.dataset.fo];s.tr++;let ok=x?.k===t.k;recordChoice(ok,ok&&s.tr===1);let f=r.querySelector('#ff');if(ok){s.lock=1;b.classList.add('good');if(f){f.className='feedback ok';f.textContent='잘했어!'}audio.success();let v=audio.speak('잘했어.');s.s++;s.q++;let e=E;T=setTimeout(()=>Promise.resolve(v).then(()=>{if(e===E)draw(r)}),620)}else{if(f)f.textContent='다시 찾아볼까?';audio.speak('다시 찾아볼까?');if(s.tr>=2)r.querySelector(`[data-fo="${s.c.pool.indexOf(t)}"]`)?.classList.add('hint')}}
function add(){let g=document.querySelector('#main .tile-grid');if(!g||g.querySelector('[data-sf]'))return;let a=g.querySelector('[data-go="alphabet"]'),h=g.querySelector('[data-go="hangul"]'),e='<button class="tile" data-sf="englishFind"><span class="emoji">🔎</span><b>영어 찾기</b><small>알파벳을 보고 찾아요</small></button>',k='<button class="tile" data-sf="hangulFind"><span class="emoji">가</span><b>한글 찾기</b><small>가나다 글자를 보고 찾아요</small></button>';a?a.insertAdjacentHTML('afterend',e):g.insertAdjacentHTML('beforeend',e);h?h.insertAdjacentHTML('beforebegin',k):g.insertAdjacentHTML('beforeend',k)}
const os=G.stop?.bind(G);G.startColor=r=>start('color',r);G.startShape=r=>start('shape',r);G.stop=()=>{stop();return os?.()};window.addEventListener('seowoo:route',e=>{if(e.detail?.route==='language')add()});document.addEventListener('click',e=>{let x=e.target.closest?.('[data-sf],[data-fr],[data-fb]');if(!x)return;e.preventDefault();e.stopPropagation();if(x.dataset.sf)start(x.dataset.sf);else if(x.dataset.fr)start(x.dataset.fr);else{stop();window.SeowooApp?.go(x.dataset.fb||'home')}},true);add();window.SeowooFindGames={start,stop};
})();
