const fs=require('fs'),assert=require('assert');
const js=fs.readFileSync('js/screen-lock.js','utf8');
const css=fs.readFileSync('css/screen-lock.css','utf8');
const html=fs.readFileSync('index.html','utf8');
const native=fs.readFileSync('android-kiosk/app/src/main/java/io/github/pswgames/seowoo/MainActivity.java','utf8');
const manifest=fs.readFileSync('android-kiosk/app/src/main/AndroidManifest.xml','utf8');
const setup=fs.readFileSync('android-kiosk/tools/Y700_SETUP_COMPLETE_LOCK.bat','utf8');
assert(js.includes("CREDENTIAL_KEY='seowoo-screen-lock-pin-v2'"));
assert(js.includes("digest('SHA-256'"));
assert(js.includes("PIN_RE=/^\\d{4,8}$/"));
assert(js.includes('nativeStrictReady'));
assert(js.includes('isProfileOwner'));
assert(js.includes('Profile Owner'));
assert(js.includes('strictLockBlocked'));
assert(!js.includes('HOLD_MS'));
assert(!css.includes('seowoo-lock-hold'));
assert(native.includes('isProfileOwnerApp'));
assert(native.includes('setLockTaskPackages'));
assert(native.includes('DevicePolicyManager.LOCK_TASK_FEATURE_NONE'));
assert(native.includes('addPersistentPreferredActivity'));
assert(native.includes('clearPackagePersistentPreferredActivities'));
assert(native.includes('android.settings.USER_SETTINGS'));
assert(native.includes('Settings.ACTION_SETTINGS'));
assert(!native.includes('Settings.ACTION_USER_SETTINGS'));
assert(!native.includes('BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE'));
assert(manifest.includes('android:lockTaskMode="normal"'));
assert(manifest.includes('android.intent.category.HOME'));
assert(!manifest.includes('android:lockTaskMode="if_whitelisted"'));
assert(setup.includes('pm get-max-users'));
assert(setup.includes('pm create-user'));
assert(setup.includes('am start-user -w'));
assert(setup.includes('set-profile-owner --user'));
assert(!setup.includes('set-device-owner'));
assert(html.includes('app-version" content="6.5.0"'));
console.log('SCREEN LOCK STATIC QA PASSED: PIN-only LockTask, Profile Owner, persistent child HOME recovery, no Device Owner/factory-reset path');
