const fs=require('fs'),assert=require('assert');
const js=fs.readFileSync('js/screen-lock.js','utf8');
const css=fs.readFileSync('css/screen-lock.css','utf8');
const html=fs.readFileSync('index.html','utf8');
assert(js.includes("CREDENTIAL_KEY='seowoo-screen-lock-pin-v2'"));
assert(js.includes("digest('SHA-256'"));
assert(js.includes("PIN_RE=/^\\d{4,8}$/"));
assert(js.includes('부모 비밀번호 설정'));
assert(js.includes('비밀번호가 맞지 않아'));
assert(!js.includes('HOLD_MS'));
assert(!js.includes('startHold'));
assert(!css.includes('seowoo-lock-hold'));
assert(html.includes('app-version" content="6.2.0"'));
assert(html.includes('눌러서 부모 비밀번호 입력'));
console.log('SCREEN LOCK STATIC QA PASSED: PIN dialog, hashed credential, no hold gesture, 6.2.0 shell');
