#!/usr/bin/env python3
from __future__ import annotations
import asyncio, hashlib, json, math, random, re, struct, wave
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
CATALOGS=[ROOT/"audio"/"catalog.js",ROOT/"audio"/"extra-catalog.js"]
VOICE_ROOT=ROOT/"audio"/"voice"
SFX_ROOT=ROOT/"audio"/"sfx"
FILES_JS=ROOT/"audio"/"files.js"
SFX_JS=ROOT/"audio"/"sfx.js"
REPORT=ROOT/"audio"/"voice-report.json"
SR=44100
ENTRY_RE=re.compile(
    r'(?P<id>"(?:\\.|[^"\\])*")\s*:\s*\{\s*"text"\s*:\s*(?P<text>"(?:\\.|[^"\\])*")\s*,\s*"lang"\s*:\s*(?P<lang>"(?:\\.|[^"\\])*")',
    re.S,
)

def parse_catalog():
    rows=[]
    seen=set()
    for catalog in CATALOGS:
        src=catalog.read_text(encoding="utf-8")
        for m in ENTRY_RE.finditer(src):
            row={"id":json.loads(m.group("id")),"text":json.loads(m.group("text")),"lang":json.loads(m.group("lang"))}
            if row["id"] in seen: raise RuntimeError(f"duplicate catalog id: {row['id']}")
            seen.add(row["id"])
            rows.append(row)
    if len(rows)<650: raise RuntimeError(f"catalog parse incomplete: {len(rows)}")
    return rows

def relpath(lang,text):
    h=hashlib.sha1(f"{lang}\\0{text}".encode()).hexdigest()[:16]
    return f"audio/voice/{'ko' if lang.lower().startswith('ko') else 'en'}/{h}.mp3"

def jsmap(path,var,obj):
    path.write_text(f"/* Generated by scripts/generate_neural_audio.py. */\nwindow.{var}="+json.dumps(obj,ensure_ascii=False,separators=(",",":"),sort_keys=True)+";\n",encoding="utf-8")

def blank(sec): return [0.0]*max(1,int(sec*SR))
def norm(a,peak=.92):
    top=max((abs(x) for x in a),default=1)
    k=min(1,peak/top) if top else 1
    return [max(-1,min(1,x*k)) for x in a]
def wav(path,a):
    path.parent.mkdir(parents=True,exist_ok=True)
    with wave.open(str(path),"wb") as w:
        w.setnchannels(1); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes(b"".join(struct.pack("<h",int(x*32767)) for x in norm(a)))
def tone(a,start,dur,f,amp,dec=3.5,harm=((1,1),)):
    b=int(start*SR); n=min(int(dur*SR),len(a)-b)
    for i in range(max(0,n)):
        t=i/SR; env=min(1,t/.012)*math.exp(-dec*t)
        a[b+i]+=amp*env*sum(g*math.sin(2*math.pi*f*m*t) for m,g in harm)
def gliss(a,start,dur,f0,f1,amp):
    b=int(start*SR); n=min(int(dur*SR),len(a)-b); ph=0
    for i in range(max(0,n)):
        t=i/SR; p=t/dur; f=f0+(f1-f0)*p; ph+=2*math.pi*f/SR
        a[b+i]+=amp*(math.sin(math.pi*min(1,p))**.65)*math.sin(ph)
def noise(a,start,dur,amp,seed,smooth=.86):
    rng=random.Random(seed); b=int(start*SR); n=min(int(dur*SR),len(a)-b); z=0
    for i in range(max(0,n)):
        p=(i/SR)/dur; env=math.sin(math.pi*min(1,p))**.8
        z=smooth*z+(1-smooth)*rng.uniform(-1,1); a[b+i]+=amp*env*z

def make_sfx():
    SFX_ROOT.mkdir(parents=True,exist_ok=True)
    bell=((1,1),(2.01,.28),(3.98,.09))
    a=blank(1.12); tone(a,.02,.72,784,.34,3.2,bell); tone(a,.30,.80,659.25,.31,3,bell); wav(SFX_ROOT/"arrival.wav",a)
    a=blank(.12); tone(a,0,.10,720,.22,18,((1,1),(2,.16))); noise(a,0,.055,.09,11,.45); wav(SFX_ROOT/"button.wav",a)
    a=blank(1.05); gliss(a,0,.92,135,92,.13); noise(a,.02,.95,.23,21,.93); wav(SFX_ROOT/"door-open.wav",a)
    a=blank(1.05); gliss(a,0,.92,94,142,.14); noise(a,.02,.95,.24,22,.93); tone(a,.88,.13,150,.08,14); wav(SFX_ROOT/"door-close.wav",a)
    dur=2.4; a=blank(dur)
    for i in range(len(a)):
        t=i/SR; mod=.82+.18*math.sin(2*math.pi*1.25*t)
        a[i]=mod*(.085*math.sin(2*math.pi*90*t)+.035*math.sin(2*math.pi*180*t)+.018*math.sin(2*math.pi*270*t))
    wav(SFX_ROOT/"motor-loop.wav",a)
    a=blank(.62); gliss(a,0,.56,120,68,.15); noise(a,0,.5,.08,31,.94); wav(SFX_ROOT/"motor-stop.wav",a)
    a=blank(.62); tone(a,0,.30,659.25,.24,5,bell); tone(a,.16,.42,880,.22,4.5,bell); wav(SFX_ROOT/"success.wav",a)
    a=blank(1.15); noise(a,0,1.1,.34,41,.90); gliss(a,.08,.9,150,82,.07); wav(SFX_ROOT/"flush.wav",a)
    m={
      "button":{"src":"audio/sfx/button.wav","gain":.9},
      "doorOpen":{"src":"audio/sfx/door-open.wav","gain":.82},
      "doorClose":{"src":"audio/sfx/door-close.wav","gain":.82},
      "motorStart":{"src":"audio/sfx/motor-loop.wav","gain":.62,"loop":True},
      "motorStop":{"src":"audio/sfx/motor-stop.wav","gain":.72},
      "arrival":{"src":"audio/sfx/arrival.wav","gain":1},
      "success":{"src":"audio/sfx/success.wav","gain":.9},
      "flush":{"src":"audio/sfx/flush.wav","gain":.88},
    }
    jsmap(SFX_JS,"SEOWOO_SFX",m); return m

async def make_voices(rows):
    import edge_tts
    voices=await edge_tts.list_voices()
    names={v.get("ShortName"):v for v in voices}
    def pick(locale,preferred):
        if preferred in names:return preferred
        c=[v for v in voices if str(v.get("Locale","")).lower()==locale.lower()]
        if not c: raise RuntimeError(f"no voice for {locale}")
        f=[v for v in c if str(v.get("Gender","")).lower()=="female"]
        return (f or c)[0]["ShortName"]
    selected={"ko-KR":pick("ko-KR","ko-KR-SunHiNeural"),"en-US":pick("en-US","en-US-JennyNeural")}
    tune={"ko-KR":{"rate":"-6%","volume":"+12%","pitch":"+0Hz"},"en-US":{"rate":"-7%","volume":"+10%","pitch":"+0Hz"}}
    unique={}
    for r in rows: unique.setdefault((r["lang"],r["text"]),relpath(r["lang"],r["text"]))
    sem=asyncio.Semaphore(4); failures=[]; count=0; lock=asyncio.Lock()
    async def one(lang,text,rel):
        nonlocal count
        out=ROOT/rel; out.parent.mkdir(parents=True,exist_ok=True)
        if out.exists() and out.stat().st_size>1200:
            async with lock: count+=1
            return
        voice=selected.get(lang)
        if not voice: failures.append({"lang":lang,"text":text,"error":"unsupported language"}); return
        async with sem:
            err=None
            for attempt in range(1,5):
                try:
                    await edge_tts.Communicate(text=text,voice=voice,**tune[lang]).save(str(out))
                    if out.stat().st_size<=1200: raise RuntimeError(f"audio too small: {out.stat().st_size}")
                    async with lock:
                        count+=1
                        if count%25==0: print(f"Generated/verified {count}/{len(unique)} unique clips")
                    return
                except Exception as e:
                    err=repr(e)
                    try: out.unlink(missing_ok=True)
                    except Exception: pass
                    await asyncio.sleep(min(10,attempt*2.5))
            failures.append({"lang":lang,"text":text,"error":err})
    await asyncio.gather(*(one(lang,text,rel) for (lang,text),rel in unique.items()))
    if failures:
        REPORT.write_text(json.dumps({"failures":failures},ensure_ascii=False,indent=2),encoding="utf-8")
        raise RuntimeError(f"voice generation failed for {len(failures)} clips")
    mapping={r["id"]:unique[(r["lang"],r["text"])] for r in rows}
    jsmap(FILES_JS,"SEOWOO_AUDIO_FILES",mapping)
    missing=[p for p in set(mapping.values()) if not (ROOT/p).exists()]
    if missing: raise RuntimeError(f"missing generated files: {missing[:5]}")
    return {"catalog_entries":len(rows),"unique_clips":len(unique),"selected_voices":selected,"tuning":tune,"mapping_entries":len(mapping)}

async def main():
    rows=parse_catalog(); sfx=make_sfx(); info=await make_voices(rows)
    report={
      "generator":"edge-tts",
      "purpose":"fixed local voice assets for Seowoo Playground",
      **info,
      "sfx_count":len(sfx),
      "runtime_fallback":"device speechSynthesis only if local media playback fails",
      "licensing_note":"edge-tts uses Microsoft's online Edge speech service. Review provider terms before commercial redistribution; this workflow is for the current personal app.",
    }
    REPORT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps(report,ensure_ascii=False,indent=2))

if __name__=="__main__": asyncio.run(main())
